# config/meta.yml
meta_product_name: "Le Petit Guide Vert"
meta_title: "Le Petit Guide Vert - L'application compagnon pour les débutants du potager"
meta_description: "L’application incontournable pour les débutants du potager en ville !"
meta_image: "open-graph-banner.png" # should exist in `app/assets/images/`
twitter_account: "@LePetitGuideVert" # required for Twitter Cards
